# Generated by Django 6.0.6 on 2026-06-17 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_alter_chaivarity_price_chaicertificate_chaireview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaicertificate',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('ML', 'Masala'), ('EL', 'Elachi'), ('PL', 'Plain'), ('KL', 'Kiwi')], max_length=2),
        ),
        migrations.AlterField(
            model_name='store',
            name='chai_varity',
            field=models.ManyToManyField(related_name='stores', to='chai.chaivarity'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
